### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by thoraj** [casbin-net/casbin-aspnetcore#15]
We're looking into using casbin.net to handle authorization in our project. We're looking to protect and authorize access to our backend api's

We're wondering if this project is still under development or if it is abandoned?

**Comment by hsluoyz** [comment]
Hi @thoraj this project is still maintained. Is there any specific question for using it? We are happy to answer it!

/cc @Sagilio

**Comment by thoraj** [comment]
Thanks for your quick reply. Glad to hear that it is still in the works. 

I'm new to casbin, and certainly to casbin-aspnetcore, so I don't have any questions just yet. I will be looking into if the context/transformer mechanics will work for our case or if it will need extensions.
