### ISSUE TITLE
Use semantic-versioning for this project

### ISSUE THREAD

**Issue by hsluoyz** [casbin-net/casbin-aspnetcore#16]
The latest version is `0.1.0-build.71.master.51c2fd0`, it's too long and unfriendly. We should use semantic-versioning.

**Comment by hsluoyz** [comment]
@Sagilio

**Comment by Sagilio** [comment]
This version is only used to develop, we will use semantic-versioning to release as `Casbin.NET` do.

**Comment by hsluoyz** [comment]
@Sagilio but it's already released to nuget with such version: https://www.myget.org/feed/casbin-net/package/nuget/Casbin.AspNetCore

![image](https://user-images.githubusercontent.com/3787410/109371445-ec27bf00-78df-11eb-8346-fc7304a26afd.png)

**Comment by hsluoyz** [comment]
@Sagilio I suggest we don't separate master with dev branch. Just one master branch, use semantic-versioning + semantic-release to do agile development.

**Comment by Sagilio** [comment]
@hsluoyz  MyGet usually is used as the nightly version or develop test source,  so not an actual release. When we use the semantic-release to release the version, MyGet source will be unnecessary.
Dev branch like the beta branch in golang casbin repo is only for preparing the next mainline version and prerelease package (beta version). Semantic-release needs this branch to prerelease.
