### ISSUE TITLE
Use CasbinAuthorize attribute on ApiController

### ISSUE THREAD

**Issue by thoraj** [casbin-net/casbin-aspnetcore#21]
I'm trying to use Casbin to control access to an api implemented using ApiController. The API uses Jwt bearer tokens.

Will this work with the CasbinAuthorize attribute?

Replacing the standard Authorize(Policy="...) attribute with CasbinAuthorize() does not seem to work. Checking the ClaimsIdentity inside a RequestTransformer shows that the User is not authenticated, and the claims array is empty. 

Furthermore I'm redirected to login and gets a 404, instead of the expected 401 error. 

So I'm wondering if the CasbinAuthorize attribute is supposed to work for thins kind of use-case? 

If not, are there plans to cover use cases with bearer tokens?

**Comment by hsluoyz** [comment]
@Sagilio

**Comment by thoraj** [comment]
The redirect is because of config issues in my Startup.cs

But it would be good to know whether you believe the Middleware and CasbinAuthorize attribute should work OK when using bearer token authentication.

**Comment by thoraj** [comment]
Seems to be working with bearer token , but I have to use both standard and casbin attribute:
```
[Authorize]
[CasbinAuthorize]
public IActionResult MyAction(...)

```
Is this intended?

**Comment by Sagilio** [comment]
Is this code work? :
```csharp
[CasbinAuthorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
public IActionResult MyAction(...)
```

**Comment by Sagilio** [comment]
> Seems to be working with bearer token , but I have to use both standard and casbin attribute:
> 
> ```
> [Authorize]
> [CasbinAuthorize]
> public IActionResult MyAction(...)
> ```
> 
> Is this intended?

No. 
Now, casbin middleware does not read the default policy or fallback policy in AuthorizationOptions, So it will not use the AuthenticationSchemes in the default policy.
But, I think we should not read those policies, we will provide AuthenticationSchemes options for this case.

**Comment by thoraj** [comment]
I tried `[CasbinAuthorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]`

And it works. I don't need the extra [Authorize] attribute, and I get 401 when token is missing as expected.   

Then I removed `AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme` And it still works. Now I'm not able reprodue the issue.
