### ISSUE TITLE
Casbin.Net assembly version

### ISSUE THREAD

**Issue by thoraj** [casbin-net/casbin-aspnetcore#23]
When adding the freshest packages for Casbin.Net and Casbin.AspNetCore I get assembly load errors. 

I think it may be because the latest released Casbin.Net is v1.5.1 while Casbin.AspNetCore expects v1.5.0

Should the package version in Casbin.AspNetCore perhaps be updated to Casbin.Net v1.5.1 ?

**Comment by hsluoyz** [comment]
@Sagilio

**Comment by Sagilio** [comment]
Casbin.NET v1.5.2 has been fixed it and Casbin.AspNetCore v0.2.1 has used this new version. You can have a try.

**Comment by hsluoyz** [comment]
https://github.com/casbin-net/casbin-aspnetcore/releases/tag/v0.2.1

**Comment by thoraj** [comment]
Works ok now with v0.2.1 👍
