### ISSUE TITLE
Typo in sample policy file? Get should be GET?

### ISSUE THREAD

**Issue by LeiYangGH** [casbin-net/casbin-aspnetcore#25]
I cloned and ran the sample. after some experiments, I found that if in [basic_policy.csv](https://github.com/casbin-net/casbin-aspnetcore/blob/master/samples/WebApplicationSample/CasbinConfigs/basic_policy.csv), `GET` works but `Get` not work.
1. I searched and found this issue [Case Insensitive Policy Enforcement](https://github.com/casbin/casbin/issues/694), and it means casbin is case sensitive. so i assue this sample has a minor typo.
2. I searched the entire library code, didn't find anywhere to specify the action of `GET` or `POST`, etc. could you please explain a little why in policy.csv the action syntax must be all upper case? Is it related to some http specification? Is it implement dependent(is the behaviour related to operation system/browser versions)?

**Comment by Sagilio** [comment]
Thank you! I will fix the typo later.

https://github.com/casbin-net/casbin-aspnetcore/blob/e5dc07746742f04ed17e2c9ebb07b34baa1e6585/src/Casbin.AspNetCore.Core/Transformers/KeyMatchRequestTransformer.cs#L16

It use c.HttpContext.Request.Method directly now, so the format like `GET`, `POST`.

**Comment by pspeybro** [comment]
there is another typo in a folder name: https://github.com/casbin-net/casbin-aspnetcore/tree/master/src/Casbin.AspNetCore.**Astractions**

I suppose this needs to be Abstractions

**Comment by hsluoyz** [comment]
@sagilio any update on this issue?

**Comment by pspeybro** [comment]
I guess this is (at least partially) closed by https://github.com/casbin-net/casbin-aspnetcore/pull/39

**Comment by hsluoyz** [comment]
Fixed in: https://github.com/casbin-net/casbin-aspnetcore/pull/39
