### ISSUE TITLE
Typo in sample basic_policy.csv: Get or GET?

### ISSUE THREAD

**Issue by LeiYangGH** [casbin-net/casbin-aspnetcore#26]
I cloned and ran the sample. After some experiments, I found that in [basic_policy.csv](https://github.com/casbin-net/casbin-aspnetcore/blob/master/samples/WebApplicationSample/CasbinConfigs/basic_policy.csv), `GET` works but `Get` not work.
1. I searched and found this issue [Case Insensitive Policy Enforcement](https://github.com/casbin/casbin/issues/694), and it means casbin is case sensitive. so i assue this sample has a minor typo.
2. I searched the entire library code, didn't find any hardcoded action string of `GET` or `POST`, etc. Could you please explain a little why in `policy.csv` the action syntax must be all upper case? Is it related to some http specification? Is it implement dependent(is the behaviour related to operation system/browser versions)?

**Comment by hsluoyz** [comment]
@Sagilio

**Comment by Sagilio** [comment]
@hsluoyz Maybe same to issue #25
