### ISSUE TITLE
Fix GitHub Actions error

### ISSUE THREAD

**Issue by hsluoyz** [casbin-net/casbin-aspnetcore#32]
https://github.com/casbin-net/casbin-aspnetcore/runs/3600508395?check_suite_focus=true

![image](https://user-images.githubusercontent.com/3787410/133294924-ff97ae15-8353-44cd-9ec9-27da338e5a1e.png)

**Comment by hsluoyz** [comment]
@sagilio

**Comment by sagilio** [comment]
It is healthy now. 
![image](https://user-images.githubusercontent.com/42855245/140548877-d8484e1f-7a48-4b00-ab19-ead0c1337ab7.png)
