### ISSUE TITLE
How to pass a custom EnforcerService or how to make dbcontext available to RequestTransformer 

### ISSUE THREAD

**Issue by slinders1985** [casbin-net/casbin-aspnetcore#38]
I am trying to retrieve objects from our db, based on ids passed by the request, to the enforcer, so that these objects are passed to a custom function when evaluating a policy. 

I have created a CustomRequestTransformer (base class BasicRequestTransformer). 
Two of the request values I retrieve within this transformer are the oid of the user and a reference id of a tenant. With these ids I want to be able to get the User and Customer object in our database. So that I can return these objects in the requestValues-object of TransfromAsync and so pass them on to the enforcer in DefaultEnforcerService (line 88). 

Is there a way to pass the dbcontext with the CustomRequestTransformer through dependency injection when configuring the DefaultRequestTransformer in the services.AddCasbinAuthorization()?
Or is there a way to pass a custom EnforcerService instead of the services.TryAddScoped<IEnforceService, DefaultEnforcerService>(); within AddCasbinAtuhorizationCore().
Or is there another way to enable this?

**Comment by hsluoyz** [comment]
@sagilio

**Comment by slinders1985** [comment]
At the moment I have found a - not so recommendable - solution, as the following warning is shown on the line
var sp = services.BuildServiceProvider(); >> "ASP0000: Calling 'BuildServiceProvider' from application code results in an additional copy of singleton services being created. Consider alternatives such as dependency injection services as parameters to 'Configure'." 
In the DefaultEnforcerFactory we have the option of passing the IServiceProvider, but in DefaultRequestTransformer that option is not available. 

![image](https://user-images.githubusercontent.com/55789119/150744448-ef1e02f1-a468-4fa8-bd02-7cf06d69e31d.png)

Any suggestions?

**Comment by sagilio** [comment]
1. You can get the DbContext from the HttpContext.RequestServices:
![image](https://user-images.githubusercontent.com/42855245/151108470-846d6cf1-578b-4e23-8c3a-d8ae2cd0bada.png)
2. All services be added in the container by the `TryAdd` function, you can add your custom service before `AddCasbinAtuhorizationCore()`. Or replace it after `AddCasbinAtuhorizationCore()`.

**Comment by slinders1985** [comment]
@sagilio Thank you for this clarification! :pray:
