### ISSUE TITLE
Missing compatibility with Casbin EFCore Adapter

### ISSUE THREAD

**Issue by shayura** [casbin-net/casbin-aspnetcore#41]
As it stands now, the only implementation of `IEnforcerProvider` inside this package, i.e. `DefaultEnforcerProvider`, does not integrate with [Casbin EFCore Adapter](https://github.com/casbin-net/EFCore-Adapter).

Would you consider adding a `ICasbinAuthorizationPolicyProvider` compatible with the EFCore Adapter?

**Comment by gsw945** [comment]
same question +1

**Comment by hsluoyz** [comment]
@AsakusaRinne @sagilio

**Comment by sagilio** [comment]
@gsw945 @shayura You can refer to [this ](https://github.com/casbin-net/casbin-aspnetcore/issues/17#issuecomment-796658834) to integrate the adapter on the current version.

We are trying a friendlier way to integrate it.

**Comment by hsluoyz** [comment]
@AsakusaRinne plz work on this

**Comment by AsakusaRinne** [comment]
> @AsakusaRinne plz work on this

It's on process now. I would submit a PR  depending on [this PR for efcore-adapter](https://github.com/casbin-net/efcore-adapter/pull/62)

**Comment by AsakusaRinne** [comment]
@shayura  We have added a sample to integrate with ```efcore-adapter``` (in ```samples/WebApplicationWithEfcoreSample```). Does it get the point of what you need?

**Comment by hsluoyz** [comment]
Closed as resolved
