### ISSUE TITLE
Support for imperative authorization checks

### ISSUE THREAD

**Issue by shayura** [casbin-net/casbin-aspnetcore#42]
I have an application that uses [imperative access control](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/resourcebased?view=aspnetcore-5.0). In this application I cannot use attributes to enforce access to a controller action because the subject, object, and action needed to query the enforcer depend upon conditions that aren't available until much later.

Do you think this package already supports imperative authorization checks, e.g. using custom request transformers, or does it need an extra layer of code that's not there yet?

**Comment by VictorioBerra** [comment]
You will need to roll your own `AuthorizationHandler<T>` and make a requirement that takes your conditions.

**Comment by hsluoyz** [comment]
@sagilio

**Comment by sagilio** [comment]
This feature already be supported, you can see some samples here: https://github.com/casbin-net/casbin-aspnetcore/blob/master/test/Casbin.AspNetCore.Tests/AuthorizationServiceTest.cs

We will provide more friendly APIs about this in future versions.

**Comment by hsluoyz** [comment]
@shayura

**Comment by hsluoyz** [comment]
Closed as resolved
