### ISSUE TITLE
Fix CI error of codeql anaylzer

### ISSUE THREAD

**Issue by hsluoyz** [casbin-net/casbin-aspnetcore#48]
See: https://github.com/casbin-net/casbin-aspnetcore/runs/7634763707?check_suite_focus=true

![image](https://user-images.githubusercontent.com/3787410/182412120-5b3af731-615e-4ee1-9457-2272bd0743e4.png)

**Comment by hsluoyz** [comment]
@sagilio

**Comment by sagilio** [comment]
@AsakusaRinne We may need to set up other version SDKs in codeql action

**Comment by AsakusaRinne** [comment]
> @AsakusaRinne We may need to set up other version SDKs in codeql action

OK, I'll try it later today

**Comment by sagilio** [comment]
@AsakusaRinne ref:
https://github.com/casbin-net/casbin-aspnetcore/blob/26c4745408c04c12fa5adda52deca349c6d223af/.github/workflows/build.yml#L25-L33
