### ISSUE TITLE
Best way to use EF core adapter with filter

### ISSUE THREAD

**Issue by kostazol** [casbin-net/casbin-aspnetcore#53]
Hi. 
I saw some questions: https://github.com/casbin-net/casbin-aspnetcore/issues/17 , https://github.com/casbin-net/casbin-aspnetcore/issues/34 , https://github.com/casbin-net/casbin-aspnetcore/issues/36 , https://github.com/casbin-net/casbin-aspnetcore/issues/37 , https://github.com/casbin-net/casbin-aspnetcore/issues/41 .
Also I saw example https://github.com/casbin-net/casbin-aspnetcore/tree/preview/samples/WebApplicationWithEfcoreSample (thank you for it).

But if I understand all correct, now a default provider not use filters. As I saw in source code a default behaviour for adapters are to load all policies on initialization. But not for optimization the EF core adapter has a lazy loading (when we load zero policies on initialization). Will I need to implement a custom provider for this variant if I want to load policies with a filter before call enforce?

**Comment by hsluoyz** [comment]
@kostazol yes, the EF core adapter is a filtered adapter, so you can do sharding by calling `LoadFilteredPolicy()`

- https://casbin.org/docs/policy-subset-loading
- https://casbin.org/docs/performance

**Comment by hsluoyz** [comment]
Closed for now, ping it back if you have any further issues
