### ISSUE TITLE
Using query or route params in CasbinAuthorizeAttribute

### ISSUE THREAD

**Issue by kostazol** [casbin-net/casbin-aspnetcore#54]
Hello. How can I use query or route params in the CasbinAuthorize? Do I need write a custom transformers for it?

**Comment by hsluoyz** [comment]
@AsakusaRinne 

/cc @sagilio

**Comment by hsluoyz** [comment]
@kostazol yes, you can implement a custom transformer based on: https://github.com/casbin-net/casbin-aspnetcore/blob/26c4745408c04c12fa5adda52deca349c6d223af/src/Casbin.AspNetCore.Core/Transformers/RequestTransformer.cs
