### ISSUE TITLE
Ef core example - WebApplicationWithEfcoreSample

### ISSUE THREAD

**Issue by OleksiiSydorov** [casbin-net/casbin-aspnetcore#64]
I have downloaded WebApplicationWithEfcoreSample sample app, and when i'm trying to run it, recieving such error - 
![vpn_conf_general](https://github.com/casbin-net/casbin-aspnetcore/assets/87321239/95691731-8238-4091-ab5b-443f89025bb1)
and slightly changed sample .csproj file, modified/added - ` <PackageReference Include="Casbin.AspNetCore" Version="1.1.0" />
    <PackageReference Include="Casbin.NET.Adapter.EFCore" Version="2.1.0" /> `

**Comment by Tanyuu** [comment]
Get, Preliminary judgment is that it is due to the Casbin.net version is not correct in the Casbin.AspNetCore.Authorization csproj file. I will further confirm and fix it in the next two days.

**Comment by OleksiiSydorov** [comment]
@Tanyuu Yes you are right. When i changed EfCore adapter to version 2.0.0-preview.1 example started working for me.
` <PackageReference Include="Casbin.AspNetCore" Version="1.1.0" />  <PackageReference Include="Casbin.NET.Adapter.EFCore" Version="2.0.0-preview.1" />`
